fast debug drawing and capsule height and width fix
briansemrau/godot_box2d pull request #36
Opened 2020-12-10 22:31 UTC by jordo

This has faster debug drawing which improves performance significantly when is_debugging_collisions_hint is turned on.

Also includes capsule fixture fix.

2020-12-10 22:34 UTC, jordo commented
Just note on this PR, this is kinda clobbering this:  (reverted some things).  

```
			if (body && is_contact_monitor_enabled()) {
				for (int i = 0; i < get_contact_count(); i++) {
					Vector2 point = get_box2dworld_transform().xform_inv(get_contact_world_pos(i));
					draw_rect(Rect2(point + Point2(-1.0f, -1.0f), Size2(2.0f, 2.0f)), Color(1.0f, 1.0f, 0.0f));
```

2020-12-10 22:34 UTC, jordo commented
Up for discussion how to do this, but this looks like we just want to show contacts as well for each body?

2020-12-10 23:11 UTC, briansemrau commented
I hadn't really decided whether we should or how to go about drawing debug contacts. In the future I think they should be made useful for debugging advanced collision logic.

2020-12-10 23:15 UTC, briansemrau requested changes

2020-12-10 23:15 UTC, briansemrau commented on scene/2d/box2d_fixtures.cpp
>  				body_node = new_body;
We should disconnect signals before we reassign body_node. (if body_node != null)

2020-12-11 02:28 UTC, briansemrau approved these changes

2020-12-11 02:41 UTC, merged